/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface NFTDescriptorTestInterface extends ethers.utils.Interface {
  functions: {
    "addressToString(address)": FunctionFragment;
    "constructTokenURI(tuple)": FunctionFragment;
    "feeToPercentString(uint24)": FunctionFragment;
    "fixedPointToDecimalString(uint160,uint8,uint8)": FunctionFragment;
    "getGasCostOfConstructTokenURI(tuple)": FunctionFragment;
    "svgImage(address,address)": FunctionFragment;
    "tickToDecimalString(int24,int24,uint8,uint8,bool)": FunctionFragment;
    "tokenToColorHex(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addressToString",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "constructTokenURI",
    values: [
      {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feeToPercentString",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fixedPointToDecimalString",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfConstructTokenURI",
    values: [
      {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "svgImage",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tickToDecimalString",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToColorHex",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "constructTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeToPercentString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fixedPointToDecimalString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfConstructTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "svgImage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tickToDecimalString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenToColorHex",
    data: BytesLike
  ): Result;

  events: {};
}

export class NFTDescriptorTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: NFTDescriptorTestInterface;

  functions: {
    addressToString(
      _address: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "addressToString(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    constructTokenURI(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "constructTokenURI(tuple)"(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    feeToPercentString(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "feeToPercentString(uint24)"(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    fixedPointToDecimalString(
      sqrtRatioX96: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "fixedPointToDecimalString(uint160,uint8,uint8)"(
      sqrtRatioX96: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getGasCostOfConstructTokenURI(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getGasCostOfConstructTokenURI(tuple)"(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    svgImage(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "svgImage(address,address)"(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    tickToDecimalString(
      tick: BigNumberish,
      tickSpacing: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      flipRatio: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "tickToDecimalString(int24,int24,uint8,uint8,bool)"(
      tick: BigNumberish,
      tickSpacing: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      flipRatio: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    tokenToColorHex(
      token: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "tokenToColorHex(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  addressToString(_address: string, overrides?: CallOverrides): Promise<string>;

  "addressToString(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<string>;

  constructTokenURI(
    params: {
      token1: string;
      token0: string;
      token0Symbol: string;
      token1Symbol: string;
      token0Decimals: BigNumberish;
      token1Decimals: BigNumberish;
      flipRatio: boolean;
      tickLower: BigNumberish;
      tickUpper: BigNumberish;
      tickSpacing: BigNumberish;
      fee: BigNumberish;
      liquidity: BigNumberish;
      poolAddress: string;
    },
    overrides?: CallOverrides
  ): Promise<string>;

  "constructTokenURI(tuple)"(
    params: {
      token1: string;
      token0: string;
      token0Symbol: string;
      token1Symbol: string;
      token0Decimals: BigNumberish;
      token1Decimals: BigNumberish;
      flipRatio: boolean;
      tickLower: BigNumberish;
      tickUpper: BigNumberish;
      tickSpacing: BigNumberish;
      fee: BigNumberish;
      liquidity: BigNumberish;
      poolAddress: string;
    },
    overrides?: CallOverrides
  ): Promise<string>;

  feeToPercentString(
    fee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "feeToPercentString(uint24)"(
    fee: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  fixedPointToDecimalString(
    sqrtRatioX96: BigNumberish,
    token0Decimals: BigNumberish,
    token1Decimals: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "fixedPointToDecimalString(uint160,uint8,uint8)"(
    sqrtRatioX96: BigNumberish,
    token0Decimals: BigNumberish,
    token1Decimals: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getGasCostOfConstructTokenURI(
    params: {
      token1: string;
      token0: string;
      token0Symbol: string;
      token1Symbol: string;
      token0Decimals: BigNumberish;
      token1Decimals: BigNumberish;
      flipRatio: boolean;
      tickLower: BigNumberish;
      tickUpper: BigNumberish;
      tickSpacing: BigNumberish;
      fee: BigNumberish;
      liquidity: BigNumberish;
      poolAddress: string;
    },
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfConstructTokenURI(tuple)"(
    params: {
      token1: string;
      token0: string;
      token0Symbol: string;
      token1Symbol: string;
      token0Decimals: BigNumberish;
      token1Decimals: BigNumberish;
      flipRatio: boolean;
      tickLower: BigNumberish;
      tickUpper: BigNumberish;
      tickSpacing: BigNumberish;
      fee: BigNumberish;
      liquidity: BigNumberish;
      poolAddress: string;
    },
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  svgImage(
    token0: string,
    token1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "svgImage(address,address)"(
    token0: string,
    token1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  tickToDecimalString(
    tick: BigNumberish,
    tickSpacing: BigNumberish,
    token0Decimals: BigNumberish,
    token1Decimals: BigNumberish,
    flipRatio: boolean,
    overrides?: CallOverrides
  ): Promise<string>;

  "tickToDecimalString(int24,int24,uint8,uint8,bool)"(
    tick: BigNumberish,
    tickSpacing: BigNumberish,
    token0Decimals: BigNumberish,
    token1Decimals: BigNumberish,
    flipRatio: boolean,
    overrides?: CallOverrides
  ): Promise<string>;

  tokenToColorHex(token: string, overrides?: CallOverrides): Promise<string>;

  "tokenToColorHex(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addressToString(
      _address: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "addressToString(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<string>;

    constructTokenURI(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    "constructTokenURI(tuple)"(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    feeToPercentString(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "feeToPercentString(uint24)"(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    fixedPointToDecimalString(
      sqrtRatioX96: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "fixedPointToDecimalString(uint160,uint8,uint8)"(
      sqrtRatioX96: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getGasCostOfConstructTokenURI(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfConstructTokenURI(tuple)"(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    svgImage(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "svgImage(address,address)"(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    tickToDecimalString(
      tick: BigNumberish,
      tickSpacing: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      flipRatio: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    "tickToDecimalString(int24,int24,uint8,uint8,bool)"(
      tick: BigNumberish,
      tickSpacing: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      flipRatio: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    tokenToColorHex(token: string, overrides?: CallOverrides): Promise<string>;

    "tokenToColorHex(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addressToString(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addressToString(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    constructTokenURI(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "constructTokenURI(tuple)"(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeToPercentString(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "feeToPercentString(uint24)"(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fixedPointToDecimalString(
      sqrtRatioX96: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fixedPointToDecimalString(uint160,uint8,uint8)"(
      sqrtRatioX96: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfConstructTokenURI(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfConstructTokenURI(tuple)"(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    svgImage(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "svgImage(address,address)"(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tickToDecimalString(
      tick: BigNumberish,
      tickSpacing: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      flipRatio: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tickToDecimalString(int24,int24,uint8,uint8,bool)"(
      tick: BigNumberish,
      tickSpacing: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      flipRatio: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenToColorHex(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenToColorHex(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addressToString(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addressToString(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    constructTokenURI(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "constructTokenURI(tuple)"(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeToPercentString(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "feeToPercentString(uint24)"(
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fixedPointToDecimalString(
      sqrtRatioX96: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "fixedPointToDecimalString(uint160,uint8,uint8)"(
      sqrtRatioX96: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfConstructTokenURI(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfConstructTokenURI(tuple)"(
      params: {
        token1: string;
        token0: string;
        token0Symbol: string;
        token1Symbol: string;
        token0Decimals: BigNumberish;
        token1Decimals: BigNumberish;
        flipRatio: boolean;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        tickSpacing: BigNumberish;
        fee: BigNumberish;
        liquidity: BigNumberish;
        poolAddress: string;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    svgImage(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "svgImage(address,address)"(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tickToDecimalString(
      tick: BigNumberish,
      tickSpacing: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      flipRatio: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tickToDecimalString(int24,int24,uint8,uint8,bool)"(
      tick: BigNumberish,
      tickSpacing: BigNumberish,
      token0Decimals: BigNumberish,
      token1Decimals: BigNumberish,
      flipRatio: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenToColorHex(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenToColorHex(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
